version: '3.8'

networks:
  my_overlay_network:
    driver: overlay

volumes:
  redis_data:

services:
  redis-server:
    image: redis:6.2.6
    networks:
      - my_overlay_network
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  backend:
    image: python:3.9.7-slim
    working_dir: /app
    volumes:
      - ../backend:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
        python app.py"
    networks:
      - my_overlay_network
    depends_on:
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: node:14.17.6-alpine
    working_dir: /app
    volumes:
      - ../frontend:/app
    command:  >
      sh -c "npm install &&
        npm start"
    ports:
      - "3000:3000"
    networks:
      - my_overlay_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.21.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my_overlay_network
    depends_on:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
