networks:
  my_bridge_network:
    driver: bridge

volumes:
  redis_data:

services:
  redis:
    image: redis:6.2.6
    container_name: redis-server
    networks:
      - my_bridge_network
    volumes:
      - redis_data:/data
  
  backend:
    image: python:3.9.7-slim
    container_name: backend
    working_dir: /app
    volumes:
      - ../backend:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
        python app.py"
    networks:
      - my_bridge_network
    depends_on:
      - redis

  frontend:
    image: node:14.17.6-alpine
    container_name: node_frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    command:  >
      sh -c "npm install &&
        npm start"
    ports:
      - "3000:3000"
    networks:
      - my_bridge_network

  nginx:
    image: nginx:1.21.3
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - my_bridge_network
    depends_on:
      - frontend